In [1]:
import numpy as np 
import pandas as pd 
import ast 
import nltk

In [2]:
df_anime=pd.read_csv('AnimeList.csv')
df_movies=pd.read_csv('Movies.csv')
df_Tvshows=pd.read_csv('Tvshows.csv')



#1st anime---------------

df_anime.head()

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,background,premiered,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Inu x Boku SS was licensed by Sentai Filmworks...,Winter 2012,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ..."
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,NaN,Spring 2007,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi..."
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,NaN,Fall 2008,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ..."
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Princess Tutu aired in two parts. The first pa...,Summer 2002,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ..."
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,NaN,Fall 2012,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)..."

In [3]:
##rename the 'genre'------> 'genres'
##rename the 'anime_id'------> 'id'
df_anime.rename(columns={'genre': 'genres'}, inplace=True)
df_anime.rename(columns={'anime_id': 'id'}, inplace=True)
df_anime.head()

,id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,background,premiered,broadcast,related,producer,licensor,studio,genres,opening_theme,ending_theme
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Inu x Boku SS was licensed by Sentai Filmworks...,Winter 2012,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ..."
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,NaN,Spring 2007,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi..."
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,NaN,Fall 2008,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ..."
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Princess Tutu aired in two parts. The first pa...,Summer 2002,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ..."
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,NaN,Fall 2012,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)..."

In [4]:
df_anime= df_anime[['id','title','episodes','studio','genres']]
df_anime.head()

,id,title,episodes,studio,genres
0,11013,Inu x Boku SS,12,David Production,"Comedy, Supernatural, Romance, Shounen"
1,2104,Seto no Hanayome,26,Gonzo,"Comedy, Parody, Romance, School, Shounen"
2,5262,Shugo Chara!! Doki,51,Satelight,"Comedy, Magic, School, Shoujo"
3,721,Princess Tutu,38,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy"
4,12365,Bakuman. 3rd Season,25,J.C.Staff,"Comedy, Drama, Romance, Shounen"

In [5]:
df_anime.isnull().sum()

id             0
title          0
episodes       0
studio      5934
genres        64
dtype: int64

In [6]:
df_anime.dropna(inplace=True)

In [7]:
df_anime.duplicated().sum()

np.int64(0)

In [8]:
##split and remove spaces from the studio,genres column
df_anime['studio']=df_anime['studio'].apply(lambda x: x.split())
df_anime['genres']=df_anime['genres'].apply(lambda x: x.split())
df_anime['studio']=df_anime['studio'].apply(lambda x: [i.replace(" ","")for i in x])
df_anime['genres']=df_anime['genres'].apply(lambda x: [i.replace(" ","")for i in x])

In [9]:
#2nd : movies------------------------------------------------------

df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [10]:
df_movies=df_movies[['genres','id','keywords','title','overview']]
df_movies.head()

,genres,id,keywords,title,overview
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca..."

In [11]:
df_movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    3
dtype: int64

In [12]:
df_movies.dropna(inplace=True)
df_movies.duplicated().sum()

np.int64(0)

In [13]:
##need to fixed the genres and overview columns

def convert(obj):
    L=[]

    for i in ast.literal_eval(obj):
        L.append(i['name'])

    return L

In [14]:
df_movies['genres']=df_movies['genres'].apply(convert)
df_movies['keywords']=df_movies['keywords'].apply(convert)

df_movies.head()

,genres,id,keywords,title,overview
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca..."

In [15]:
##converting a full string(overview column) into dict of string
df_movies['overview']= df_movies['overview'].apply(lambda x: x.split())

#remove spaces from those string type columns
df_movies['genres']= df_movies['genres'].apply(lambda x :[i.replace(" ","") for i in x])
df_movies['keywords']= df_movies['keywords'].apply(lambda x :[i.replace(" ","") for i in x])
df_movies['overview']= df_movies['overview'].apply(lambda x :[i.replace(" ","") for i in x])

In [16]:
#3rd : series-------------------------------------------------

df_Tvshows.head()

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,name,vote_average,vote_count
0,False,/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg,"[10765, 9648, 35]",119051,['US'],en,Wednesday,"Smart, sarcastic and a little dead inside, Wed...",318.7812,/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg,2022-11-23,Wednesday,8.392,9781
1,False,/jCcSS9iDpKgll8Kpp7qVhSn0l1f.jpg,[18],194766,['US'],en,The Summer I Turned Pretty,"Every summer, Belly and her family head to the...",266.2929,/xBIz53wYWsKfFpN0TaizVAjKJ0z.jpg,2022-06-16,The Summer I Turned Pretty,8.173,956
2,False,/biIBy2LPOOtGCgUYOls3dUEWU3v.jpg,"[10765, 18]",157239,['US'],en,Alien: Earth,When the mysterious deep space research vessel...,229.4961,/yueXS3q8BtoWekcHOATFHicLl3e.jpg,2025-08-12,Alien: Earth,7.708,427
3,False,/aSGSxGMTP893DPMCvMl9AdnEICE.jpg,"[80, 18, 9648]",1405,['US'],en,Dexter,"Dexter Morgan, a blood spatter pattern analyst...",194.8342,/q8dWfc4JwQuv3HayIZeO84jAXED.jpg,2006-10-01,Dexter,8.215,4900
4,False,/oRdc2nn7jLOYy4fBdvmFKPsKzZE.jpg,"[80, 18, 9648]",2734,['US'],en,Law & Order: Special Victims Unit,"In the criminal justice system, sexually-based...",174.1633,/34O6znqnLHAa19mZrQB0sxTDGzH.jpg,1999-09-20,Law & Order: Special Victims Unit,7.936,4010

In [17]:
df_Tvshows=df_Tvshows[['id','genre_ids','name','overview']]
df_Tvshows.head()

,id,genre_ids,name,overview
0,119051,"[10765, 9648, 35]",Wednesday,"Smart, sarcastic and a little dead inside, Wed..."
1,194766,[18],The Summer I Turned Pretty,"Every summer, Belly and her family head to the..."
2,157239,"[10765, 18]",Alien: Earth,When the mysterious deep space research vessel...
3,1405,"[80, 18, 9648]",Dexter,"Dexter Morgan, a blood spatter pattern analyst..."
4,2734,"[80, 18, 9648]",Law & Order: Special Victims Unit,"In the criminal justice system, sexually-based..."

In [18]:
df_Tvshows.isnull().sum()

id             0
genre_ids      0
name           0
overview     927
dtype: int64

In [19]:
df_Tvshows.dropna(inplace=True)
df_Tvshows.duplicated().sum()
df_Tvshows.drop_duplicates(inplace=True)

In [20]:
# 1. Define the TMDB TV Genre Mapping
genre_map = {
    10759: "Action&Adventure", 16: "Animation", 35: "Comedy", 80: "Crime", 
    99: "Documentary", 18: "Drama", 10751: "Family", 10762: "Kids", 
    9648: "Mystery", 10763: "News", 10764: "Reality", 10765: "SciFi&Fantasy", 
    10766: "Soap", 10767: "Talk", 10768: "War&Politics", 37: "Western"
}

df_Tvshows['genres']=df_Tvshows['genre_ids'].apply(lambda x: [genre_map[i] for i in x if i in genre_map])
##rename the 'name'------> 'title'
df_Tvshows.rename(columns={'name': 'title'}, inplace=True)

In [21]:
##converting a full string(overview column) into dict of string
df_Tvshows['overview']=df_Tvshows['overview'].apply(lambda x : x.split())
#remove spaces from sentence
df_Tvshows['overview']=df_Tvshows['overview'].apply(lambda x:[i.replace(" ","") for i in x])

In [22]:
##now merge these 3 datasets datas into a single column---------> tags

df_movies['tags']= df_movies['genres']+df_movies['keywords']+df_movies['overview']

df_Tvshows['tags']= df_Tvshows['genres']+df_Tvshows['overview']

df_anime['tags']= df_anime['genres']+df_anime['studio']

In [23]:
##now add a new column content_type for these 3 datasets

df_anime['content_type']='Anime'
df_movies['content_type']='Movie'
df_Tvshows['content_type']='Tvshows'

##now the needed column should only exist

df_newanime= df_anime[['id','title','tags','content_type']]
df_newmovies= df_movies[['id','title','tags','content_type']]
df_newTvshows= df_Tvshows[['id','title','tags','content_type']]

In [24]:
##finally merge these 3 datasets and creating the model

main_df= pd.concat([df_newanime, df_newmovies, df_newTvshows], ignore_index=True)

# Convert the 'tags' list back into a single string for Text Vectorization
main_df['tags']= main_df['tags'].apply(lambda x:" ".join(x))
main_df['tags']= main_df['tags'].apply(lambda x: x.lower())

main_df.tail()

,id,title,tags,content_type
22140,13531,The Beatles,the beatles is an american animated television...,Tvshows
22141,73068,Begin Again,a variety show gathering some of korea’s best ...,Tvshows
22142,12146,Shelley,"james shelley, an educated, sardonic, permanen...",Tvshows
22143,91678,Queendom,a musical battle between 6 trending girl group...,Tvshows
22144,15716,Equinox,equinox was a long-running channel 4 popular s...,Tvshows

In [25]:
## Text vectorization
from sklearn.feature_extraction.text import CountVectorizer

#We want the top 5000 most frequent words to avoid "noise"
# We also remove stop words like "the", "a", "is"
cv= CountVectorizer(max_features=5000, stop_words='english')

In [26]:
from nltk.stem.porter import PorterStemmer ##to remove the same tense words in this column
ps=PorterStemmer()

In [27]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)


main_df['tags'].apply(stem)
main_df.tail()

,id,title,tags,content_type
22140,13531,The Beatles,the beatles is an american animated television...,Tvshows
22141,73068,Begin Again,a variety show gathering some of korea’s best ...,Tvshows
22142,12146,Shelley,"james shelley, an educated, sardonic, permanen...",Tvshows
22143,91678,Queendom,a musical battle between 6 trending girl group...,Tvshows
22144,15716,Equinox,equinox was a long-running channel 4 popular s...,Tvshows

In [28]:
## vectorize my data
vectors= cv.fit_transform(main_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(22145, 5000))

In [29]:
#now use cosine similarity to find the movies from user interest

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)
similarity.shape

(22145, 22145)

In [30]:

import joblib


# 4. Save to files (THE BETTER BRIDGE TO STREAMLIT)
# It's common to keep the .pkl extension, or use .joblib
joblib.dump(main_df, 'main_df.joblib')
joblib.dump(similarity, 'similarity.joblib')

['similarity.joblib']